language: php

php:
  - 7.4

addons:
  chrome: stable

services:
  - mysql
  
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot
  - sudo service mysql restart
  
install:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - composer require --dev laravel/dusk
  - php artisan dusk:chrome-driver

before_script:
  - cp .env.example .env
  - mysql --user="root" --password="root" -e "CREATE DATABASE laravel;"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk
