language: php

php:
  - 7.4

addons:
  chrome: stable

services:
  - mysql
  
install:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - composer require --dev laravel/dusk
  - php artisan dusk:chrome-driver

before_script:
  - cp .env.example .env
  - mysql --user="root" --password="root" -e "CREATE DATABASE my-database character set UTF8mb4 collate utf8mb4_bin;"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk
