name: Laravel
on:
  push:
    branches:
    - master
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy ENV Laravel Configuration for CI
      run: sudo apt-get install php && php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies (PHP vendors)
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: cd /home/runner/work/laravel/laravel/ && php artisan key:generate && php artisan config:cache
    - name: Create DB and schemas
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y mysql-server mysql-client
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php vendor/bin/phpunit --coverage-text --colors=never && composer require --dev laravel/dusk && php artisan dusk:chrome-driver
    - name: Google Chrome
      run: google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - name: Execute laravel
      run: php artisan serve &
